version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Porta padrão do RabbitMQ
      - "15672:15672" # Porta da interface web do RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fast-food
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

  orders-app:
    build: ./orders
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: postgres://user:password@db/dbname
      RABBITMQ_URL: amqp://user:password@rabbitmq
    volumes:
      - ./orders:/usr/src/app
    depends_on:
      - db
      - rabbitmq

  kitchen-app:
    build: ./kitchen
    ports:
      - "3334:3334"
    environment:
      RABBITMQ_URL: amqp://user:password@rabbitmq
    volumes:
      - ./kitchen:/usr/src/app
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
  db_data:
